apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
      - name: shopping-app
        image: ggalva/online_shop:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
