apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-nginx-gops
spec:
  project: argo-demo
  source:
    repoURL: https://github.com/gg-alva/gops.git
    targetRevision: main  
    path: D1/mani
  destination:
    server: https://kubernetes.defaut.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true     
      selfHeal: true 
